import { Container } from "@/components/Container";
import { Header } from "@/components/Header"
import { Footer } from "@/components/Footer"
import { CheckIcon } from '@heroicons/react/20/solid'
import { Faqs } from "@/components/Faqs";
import { Button } from "@/components/Button";
import Link from "next/link"
import { CallToActionLight } from "@/components/CallToActionLight";

// Web design features
const features1 = [
  {
    name: 'Admin Dashboard',
    description: "View your site's performance at any time, including page visits, user activity, and more.",
  },
  { name: 'Lead Generation', description: 'Get all of the leads generated by your website right into your inbox, as well as the admin dashboard.' },
  {
    name: 'Search Engine Optimization',
    description: 'With websites specifically desined to improve your SEO, you can be assured that your site ends up higher on search engine results.',
  },
  {
    name: 'Improved Performance',
    description: 'Instead of using WordPress in a one-size-fits-all approach, your website will be custom designed by us, leading to better performance.',
  },
  { name: 'Customizations', description: "Depending on your use case, WebSlush can suggest to you specific additions you can make to your site, such as live chat, notifications, and much more." },
  { name: 'Technical Integrations', description: 'You can also consult us for highly technical requirements, such as API integrations, digital payments, etcetera.' },
  {
    name: 'Reporting',
    description: "Receive a report of your site's performance every month, along with advertising and content creation suggestions.",
  },
  {
    name: 'Mobile app',
    description: "With modern technologies, it's possible to create an exact replica of your website as a mobile app. Get in touch with us to know more about converting a website into an app.",
  },
]
const features = [
  {
    name: "Value creation", description: "Writing articles and blogs is great way to create value and improve trust in your brand. We can write them for you!"
  },
  {
    name: "Ghostwriting", description: "You can also hire someone to write on your behalf. Hiring a professional ghostwriter is the best way for improving your presence on LinkedIn."
  },
  {
    name: "Copywriting", description: "Our team can be your sidekick, even for lead generation. We can take care of emails, ads, and content. An all-inclusive copywriting service."
  }
]
const features2 = [
  {
    name: "Complete control", description: "With automated advertisements, you control your budget and decide when and how you want to advertise."
  },
  {
    name: "Contextual Advertising", description: "All of our ads are professionally designed, with your customer in mind. Catchy themes and multiple variations help us convert better."
  },
  {
    name: "Well-designed Graphics", description: "Beautiful graphics in your ads improve it's CTR, making the campaign much more economical."
  },
  {
    name: "Sales funneling", description: "A well defined sales funnel from WebSlush will help you analyze your ads and capture more leads."
  }
]

export default function solutions() {
  return (
    <>
      <Header />
      <Container>
        {/* Heading & Subheading */}
        <div className="bg-white pt-24 pb-12 sm:py-32">
          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <div className="mx-auto max-w-2xl lg:mx-0">
              <p className="text-base font-semibold leading-7 text-indigo-600">Beyond a website</p>
              <h2 className="mt-2 text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">Solutions</h2>
              <p className="mt-6 text-lg leading-8 text-gray-600">
                A successful business online is not just built by a great website, or a high-performing ad campaign. It's need something more than that, and doing everything by yourself can be exhausting. <br /><br /> Here's how WebSlush can help you get out there:
              </p>
            </div>
          </div>
        </div>

        <hr className="border-4 w-64 mx-auto rounded-full" />

        {/* Web Design Section */}
        <div className="bg-white py-24 sm:py-32" id="web-design">
          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <div className="mx-auto grid max-w-2xl grid-cols-1 gap-x-8 gap-y-16 sm:gap-y-20 lg:mx-0 lg:max-w-none lg:grid-cols-3">
              <div>
                <div className="sticky top-24">
                  <h2 className="text-base font-semibold leading-7 text-indigo-600">Power to more</h2>
                  <p className="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Website Design</p>
                  <p className="mt-6 text-base leading-7 text-gray-600">
                    The most significant investment for your online presence you can make is a beautiful, performant, and SEO friendly website.
                  </p>
                  <div className="flex mt-5">
                    <Button className="max-w-md">
                      <Link href="/contact#custom">
                        Get a quote
                      </Link>
                    </Button>
                  </div>
                </div>
              </div>
              <dl className="col-span-2 grid grid-cols-1 gap-x-8 gap-y-10 text-base leading-7 text-gray-600 sm:grid-cols-2 lg:gap-y-16">
                {features1.map((feature) => (
                  <div key={feature.name} className="relative pl-9">
                    <dt className="font-semibold text-gray-900">
                      <CheckIcon className="absolute left-0 top-1 h-5 w-5 text-indigo-500" aria-hidden="true" />
                      {feature.name}
                    </dt>
                    <dd className="mt-2">{feature.description}</dd>
                  </div>
                ))}
              </dl>
            </div>
          </div>
        </div>

        <hr className="border-4 w-64 mx-auto rounded-full" />


        {/* Content writing and Social Media Advertising Section */}
        <div className="bg-white py-24 sm:py-32" id="ad-design">
          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <div className="mx-auto grid max-w-2xl grid-cols-1 gap-x-8 gap-y-16 sm:gap-y-20 lg:mx-0 lg:max-w-none lg:grid-cols-3">
              <div>
                <div className="sticky top-24">
                  <h2 className="text-base font-semibold leading-7 text-indigo-600">Everything you need</h2>
                  <p className="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Advertisement Campaigns</p>
                  <p className="mt-6 text-base leading-7 text-gray-600">
                    Advertising with us is hassle free. With extreme focus on transparency, you can stay on top of things with our admin dashboard. And with targeted advertisements across multiple platforms, WebSlush can cater to any scale of advertising.
                  </p>
                </div>
              </div>
              <dl className="col-span-2 grid grid-cols-1 gap-x-8 gap-y-10 text-base leading-7 text-gray-600 sm:grid-cols-2 lg:gap-y-16">
                {features2.map((feature) => (
                  <div key={feature.name} className="relative pl-9">
                    <dt className="font-semibold text-gray-900">
                      <CheckIcon className="absolute left-0 top-1 h-5 w-5 text-indigo-500" aria-hidden="true" />
                      {feature.name}
                    </dt>
                    <dd className="mt-2">{feature.description}</dd>
                  </div>
                ))}
              </dl>
            </div>
          </div>
        </div>

        <hr className="border-4 w-64 mx-auto rounded-full" />

        {/* External Integration section */}

        <div className="bg-white py-24 sm:py-32" id="content-writing">
          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <div className="mx-auto grid max-w-2xl grid-cols-1 gap-x-8 gap-y-16 sm:gap-y-20 lg:mx-0 lg:max-w-none lg:grid-cols-3">
              <div>
                <div className="sticky top-24">
                  <h2 className="text-base font-semibold leading-7 text-indigo-600">The Power of Expression</h2>
                  <p className="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Content Creation</p>
                  <p className="mt-6 text-base leading-7 text-gray-600">
                    WebSlush can create content for you for blogging sites, such as Quora and LinkedIn.
                  </p>
                </div>
              </div>
              <dl className="col-span-2 grid grid-cols-1 gap-x-8 gap-y-10 text-base leading-7 text-gray-600 sm:grid-cols-2 lg:gap-y-16">
                {features.map((feature) => (
                  <div key={feature.name} className="relative pl-9">
                    <dt className="font-semibold text-gray-900">
                      <CheckIcon className="absolute left-0 top-1 h-5 w-5 text-indigo-500" aria-hidden="true" />
                      {feature.name}
                    </dt>
                    <dd className="mt-2">{feature.description}</dd>
                  </div>
                ))}
              </dl>
            </div>
          </div>
        </div>

        <CallToActionLight />

      </Container>
      <Footer />
    </>
  )
}